# Generated by Django 5.1.4 on 2025-01-23 14:13

import content.utils
import content.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=content.utils.video_upload_path)),
                ('thumbnail_img', models.ImageField(blank=True, null=True, upload_to=content.utils.thumbnail_upload_path, validators=[content.validators.validate_jpeg_file, content.validators.ValidateFileSize(0.3)])),
                ('genres', models.ManyToManyField(related_name='videos', to='content.genremodel')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
